"""plot3 — grammar-of-graphics plotting on three.js."""

from __future__ import annotations

from plot3.__version__ import __version__
from plot3.geoms import (
    aes,
    annotate,
    area,
    coord_3d,
    coord_equal,
    coord_polar,
    derivative,
    facet_grid,
    facet_wrap,
    geom_bar,
    geom_boxplot,
    geom_col,
    geom_density,
    geom_abline,
    geom_errorbar,
    geom_function,
    geom_hline,
    geom_histogram,
    geom_isosurface,
    geom_jitter,
    geom_label,
    geom_line,
    geom_linerange,
    geom_path,
    geom_point,
    geom_point3d,
    geom_pointrange,
    geom_ribbon,
    geom_smooth,
    geom_surface,
    geom_text,
    geom_vector_field,
    geom_vline,
    geom_violin,
    labs,
    position_dodge,
    position_fill,
    position_stack,
    stat_density_3d,
    stat_summary,
    tangent,
    scale_color_continuous,
    scale_color_viridis_c,
    scale_colour_continuous,
    scale_colour_viridis_c,
    scale_x_log10,
    scale_y_log10,
    theme,
    theme_bw,
    theme_classic,
    theme_dark,
    theme_light,
    theme_minimal,
    slider,
    transition_states,
    transition_time,
)
from plot3.compose import plot_annotation, plot_layout
from plot3.ggplot import autohide, ggsave, ggplot  # show via ggplot.show
from plot3.io import read_bin
from plot3.jupyter import (
    disable_r_style,
    enable_r_style,
    load_ipython_extension,
    register_plot3,
)
from plot3.payload import (
    PAYLOAD_VERSION,
    build_payload,
    display_payload,
    load_payload,
    render_payload,
    save_payload,
    validate_payload,
)
from plot3.remote import (
    MIME_PLOT3,
    has_craft_host,
    is_remote_kernel,
    remote_ggplot_payload,
    show_remote,
)

__all__ = [
    "ggplot",
    "aes",
    "geom_point",
    "geom_point3d",
    "geom_surface",
    "geom_isosurface",
    "stat_density_3d",
    "geom_line",
    "geom_path",
    "geom_col",
    "geom_bar",
    "geom_histogram",
    "geom_boxplot",
    "geom_density",
    "geom_function",
    "geom_vector_field",
    "geom_violin",
    "geom_jitter",
    "geom_errorbar",
    "geom_linerange",
    "geom_pointrange",
    "geom_ribbon",
    "geom_smooth",
    "stat_summary",
    "geom_hline",
    "geom_vline",
    "geom_abline",
    "geom_text",
    "geom_label",
    "annotate",
    "position_dodge",
    "position_stack",
    "position_fill",
    "area",
    "tangent",
    "derivative",
    "facet_wrap",
    "facet_grid",
    "coord_3d",
    "coord_equal",
    "coord_polar",
    "labs",
    "scale_colour_continuous",
    "scale_color_continuous",
    "scale_colour_viridis_c",
    "scale_color_viridis_c",
    "scale_x_log10",
    "scale_y_log10",
    "transition_time",
    "transition_states",
    "slider",
    "theme",
    "theme_bw",
    "theme_classic",
    "theme_dark",
    "theme_light",
    "theme_minimal",
    "ggsave",
    "plot_layout",
    "plot_annotation",
    "read_bin",
    "autohide",
    "enable_r_style",
    "disable_r_style",
    "load_ipython_extension",
    "register_plot3",
    "PAYLOAD_VERSION",
    "build_payload",
    "render_payload",
    "validate_payload",
    "save_payload",
    "load_payload",
    "display_payload",
    "MIME_PLOT3",
    "is_remote_kernel",
    "has_craft_host",
    "remote_ggplot_payload",
    "show_remote",
    "__version__",
]

# Auto-register magics when loaded inside IPython (CRAFT / Jupyter).
try:
    from IPython import get_ipython as _get_ipython

    if _get_ipython is not None and _get_ipython() is not None:
        register_plot3(quiet=False)
except Exception:
    pass
